"""empty message

Revision ID: 64e7ed46cbfd
Revises: 1470bda32ee0
Create Date: 2021-10-18 14:11:33.319484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e7ed46cbfd'
down_revision = '1470bda32ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emp', 'address')
    # ### end Alembic commands ###
