"""empty message

Revision ID: d86a8c340a39
Revises: 64e7ed46cbfd
Create Date: 2021-10-18 14:11:57.625071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86a8c340a39'
down_revision = '64e7ed46cbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emp') as batch_op:
        batch_op.drop_column('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('address', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
