"""empty message

Revision ID: e5dab62dfb86
Revises: d86a8c340a39
Create Date: 2021-10-18 14:26:21.520098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dab62dfb86'
down_revision = 'd86a8c340a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('emp', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('emp', sa.Column('pin_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emp', 'pin_code')
    op.drop_column('emp', 'state')
    op.drop_column('emp', 'address')
    # ### end Alembic commands ###
